<?php
$payment = $this->payment;
$form = $this->form;
$form->prepare();
$form->setAttribute('action', '/payments/Payment/edit');
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');

$attrs = array(
  'paymentNumber',
  'amount', 
  'status', 
  );

?>

  <h2> Payment </h2>
  <div class='tabbable'>
    <ul class='nav nav-tabs'>
      <li class='active'><a href='#payment_info' data-toggle='tab'> Informacion </a></li>
    </ul>

    <div class='tab-content'>

      <div class='tab-pane active' id='payment_info'>
        <?php
        echo $this->form()->openTag($form);
        foreach ($attrs as $attr) {
          echo $this->formRow($form->get($attr));
        }
//echo $this->formCollection($form);
        ?>
        <input type="hidden" name="paymentId" value="<?php echo $payment->getPaymentId(); ?>"/>
        <div class='form-actions'>
          <button type='submit' class='btn btn-primary'> Actualizar </button>
          <button type='submit' class='btn btn-danger' formaction="/payments/Payment/delete"> Delete </button>
        </div> 
        <?php
        echo $this->form()->closeTag($form);
        ?>
      </div>  
    </div>
  </div>

  <script>

  $("label span").each(function() {
    var $this = $(this);
    $this.replaceWith($("<label class='control-label'><strong>" + $this.html() + "</strong></label>"));
  });

  $("div label").each(function() {
    var $this = $(this);
    $this.replaceWith($("<div class='control-group'>" + $this.html() + "</div>"));
  });

  $('input').wrap('<div class="controls" />');

  </script>