<?php	
	$payments = $this->allPayments;

    $attrs = array("Amount", "Payment Number", "Date and Time", "Status");

?>

<table class='table'> 
  <thead>
    <tr>
      <?php
      foreach($attrs as $key) {
        echo "<th>" . $key . "</th>";
      }
      ?>
    </tr>
  </thead>
  <tbody>
    <?php
    foreach($payments as $tmp_payment) {
      	echo "<tr>";
    ?>
    <td><a href="<?php echo $this->url('payments/Payment', array('action'=>'show', 'paymentId' => $tmp_payment->getPaymentId() ));?>"> <?php echo $tmp_payment->getAmount(); ?> </a></td>
    <td><a href="<?php echo $this->url('payments/Payment', array('action'=>'show', 'paymentId' => $tmp_payment->getPaymentId() ));?>"> <?php echo $tmp_payment->getPaymentNumber(); ?> </a></td>
    <td><a href="<?php echo $this->url('payments/Payment', array('action'=>'show', 'paymentId' => $tmp_payment->getPaymentId() ));?>"> <?php echo $tmp_payment->getTimeStamp()->format('Y-m-d h:i:s'); ?> </a></td>
    <td><a href="<?php echo $this->url('payments/Payment', array('action'=>'show', 'paymentId' => $tmp_payment->getPaymentId() ));?>"> <?php echo $tmp_payment->getStatus(); ?> </a></td>
    <?php
    	echo "</tr>";
    }
    ?>
  </tbody>
</table>
