<?php

namespace DoctrineORMModule\Proxy\__CG__\Client\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Client extends \Client\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getClientId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["clientId"];
        }
        $this->__load();
        return parent::getClientId();
    }

    public function getAccounts()
    {
        $this->__load();
        return parent::getAccounts();
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function getStateId()
    {
        $this->__load();
        return parent::getStateId();
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getPhoneHome()
    {
        $this->__load();
        return parent::getPhoneHome();
    }

    public function getPhoneWork()
    {
        $this->__load();
        return parent::getPhoneWork();
    }

    public function getPhoneReference()
    {
        $this->__load();
        return parent::getPhoneReference();
    }

    public function getPhoneCell()
    {
        $this->__load();
        return parent::getPhoneCell();
    }

    public function getAddressHome()
    {
        $this->__load();
        return parent::getAddressHome();
    }

    public function getAddressWork()
    {
        $this->__load();
        return parent::getAddressWork();
    }

    public function getTimeStamp()
    {
        $this->__load();
        return parent::getTimeStamp();
    }

    public function setAccounts($a)
    {
        $this->__load();
        return parent::setAccounts($a);
    }

    public function setFirstName($fn)
    {
        $this->__load();
        return parent::setFirstName($fn);
    }

    public function setLastName($ln)
    {
        $this->__load();
        return parent::setLastName($ln);
    }

    public function setStateId($sId)
    {
        $this->__load();
        return parent::setStateId($sId);
    }

    public function setStatus($s)
    {
        $this->__load();
        return parent::setStatus($s);
    }

    public function setPhoneHome($ph)
    {
        $this->__load();
        return parent::setPhoneHome($ph);
    }

    public function setPhoneReference($pr)
    {
        $this->__load();
        return parent::setPhoneReference($pr);
    }

    public function setPhoneCell($pc)
    {
        $this->__load();
        return parent::setPhoneCell($pc);
    }

    public function setAddressHome($ah)
    {
        $this->__load();
        return parent::setAddressHome($ah);
    }

    public function setAddressWork($aw)
    {
        $this->__load();
        return parent::setAddressWork($aw);
    }

    public function setTimeStamp()
    {
        $this->__load();
        return parent::setTimeStamp();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'clientId', 'firstName', 'lastName', 'stateId', 'status', 'phoneHome', 'phoneWork', 'phoneReference', 'phoneCell', 'addressHome', 'addressWork', 'timeStamp', 'accounts');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}