<h2> Delete Investor </h2>
<form action='delete' method='post'>
	<p>Are you sure you want to delete investor <?php echo $this->investorId; ?> ?</p>
	<div class="form-actions">
		<input type="hidden" name="investorId" value="<?php echo $this->investorId; ?>"/>
		<button type="submit" name="sureDelete" value="yes" class="btn btn-danger"> Yes </button>
		<button type="submit" name="sureDelete" value="no" class="btn"> No </button>
	</div>
</form>
