<?php
    $client = $this->client;
    $accounts = $client->getAccounts();
    $client_html =  ucwords($client->getLastName() . ", " . $client->getFirstName());
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', '/clients/Client/edit');
    $form->setAttribute('method', 'post');
    $form->setAttribute('class', 'form-horizontal');
    $attrs = array(
        'firstName', 
        'lastName', 
        'stateId',
        'status', 
        'phoneHome', 
        'phoneWork',
        'phoneReference',
        'phoneCell',
        'addressHome',
        'addressWork',
    );
    $accountAttrs = array(
        'ID',
        'Amount',
        'Start Week',
        'Payments',
        '# Paid',
        'status'
        );

    $paymentCounts = $client->getPaymentCounts();
?>

<h2> <?php echo $client_html; ?> </h2>

<div class='tabbable'>
    <ul class='nav nav-tabs'>
        <li class='active'><a href='#client_info' data-toggle='tab'> Information </a></li>
        <li><a href='#client_accounts' data-toggle='tab'> Accounts </a></li>
    </ul>

    <div class='tab-content'>

        <div class='tab-pane active' id='client_info'>
            <div class="row-fluid">
                <div class="span6">
                    <?php
                    echo $this->form()->openTag($form);
                        foreach ($attrs as $attr) {
                            echo $this->formRow($form->get($attr));
                        }
                    ?>
                    <input type="hidden" name="clientId" value="<?php echo $client->getClientId(); ?>"/>
                    <div class='form-actions'>
                        <button type='submit' class='btn btn-primary'> Update </button>
                        <button type='submit' class='btn btn-danger' formaction="/clients/Client/delete"> Delete </button>
                    </div> 
                    <?php
                        echo $this->form()->closeTag($form);
                    ?>
                </div>
                <div class="offset1 span5" id="paymentByStatusContainer">
                    <div class="well">
                        <h3 class="text-center"> Overall Client Performance </h3>
                        <canvas id="paymentByStatusCanvas"></canvas>
                    </div>
                </div>    
            </div>
        </div>

        <div class='tab-pane' id='client_accounts'>
            <form action="/accounts/Account/request" method="post">
                <input type="hidden" name="clientId" value="<?php echo $client->getClientId(); ?>"/>
                <input type="submit" class='btn' value="Create Cuenta" formaction="/accounts/Account/request" />
            </form>
            <table class='table'> 
                <thead>
                    <tr>
                        <?php
                            if (count($accounts) !== 0) {
                                foreach($accountAttrs as $attr ) {
                                    echo "<th>" . $attr . "</th>";
                                }
                            }
                        ?>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        foreach($accounts as $tmp_account) {
                            echo "<tr>";
                    ?>
                    <td><a href="<?php echo $this->url('accounts/Account', array('action'=>'show', 'accountId' => $tmp_account->getAccountId() ));?>"> <?php echo $tmp_account->getAccountId(); ?> </a></td>
                    <td><a href="<?php echo $this->url('accounts/Account', array('action'=>'show', 'accountId' => $tmp_account->getAccountId() ));?>"> <?php echo $tmp_account->getAmount(); ?> </a></td>
                    <td><a href="<?php echo $this->url('accounts/Account', array('action'=>'show', 'accountId' => $tmp_account->getAccountId() ));?>"> <?php echo $tmp_account->getFirstPayDateStr(); ?> </a></td>
                    <td><a href="<?php echo $this->url('accounts/Account', array('action'=>'show', 'accountId' => $tmp_account->getAccountId() ));?>"> <?php echo $tmp_account->getNPayments(); ?> </a></td>
                    <td><a href="<?php echo $this->url('accounts/Account', array('action'=>'show', 'accountId' => $tmp_account->getAccountId() ));?>"> <?php echo $tmp_account->getNPaid(); ?> </a></td>
                    <td><a href="<?php echo $this->url('accounts/Account', array('action'=>'show', 'accountId' => $tmp_account->getAccountId() ));?>"> <?php echo $tmp_account->getStatus(); ?> </a></td>
                    <?php
                            echo "</tr>";
                        }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>

$("label span").each(function() {
    var $this = $(this);
    $this.replaceWith($("<label class='control-label'><strong>" + $this.html() + "</strong></label>"));
});

$("div label").each(function() {
    var $this = $(this);
    $this.replaceWith($("<div class='control-group'>" + $this.html() + "</div>"));
});

$('input').wrap('<div class="controls" />');

//Chart =====================================

var paymentByStatusCanvas = $('#paymentByStatusCanvas');
var paymentByStatusCanvasContext = paymentByStatusCanvas.get(0).getContext("2d");
var paymentByStatusContainer = $('#paymentByStatusContainer'); 

var paymentByStatusData = [
    {
        value: <?php echo $paymentCounts[\Payment\Entity\Payment::DUE]; ?>,
        color: "#bbbbbb"
    },
    {
        value: <?php echo $paymentCounts[\Payment\Entity\Payment::LATE]; ?>,
        color: "#C3BD4B"
    },
    {
        value: <?php echo $paymentCounts[\Payment\Entity\Payment::ONTIME]; ?>,
        color: "#88BF40"
    },
]

$(window).resize(respondCanvas);

function respondCanvas() {
    paymentByStatusCanvas.attr('width', paymentByStatusContainer.width() - 20);
    paymentByStatusCanvas.attr('height', 300);
    var paymentByStatusChart = new Chart(paymentByStatusCanvasContext).Doughnut(paymentByStatusData);
}

//Initial call 
respondCanvas();

//End Chart =================================

</script>