<?php
  $client = $this->client;
  $client_html =  $client->getLastName() . ", " . $client->getFirstName();
  $client_status_html = "Pending";
  $form = $this->form;
  $form->prepare();
  $form->setAttribute('action', '/clients/Client/edit');
  $form->setAttribute('method', 'post');
  $form->setAttribute('class', 'form-horizontal');
?>

<h2> <?php echo ucwords($client_html); ?> <small> <?php echo $client_status_html;?></small> </h2>
<div class='tabbable'>
  <ul class='nav nav-tabs'>
    <li class='active'><a href='#client_info' data-toggle='tab'> Informacion</a></li>
  </ul>
  
  <div class='tab-content'>
    
    <div class='tab-pane active' id='client_info'>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    ?>
    <input type="hidden" name="clientId" value="<?php echo $client->getClientId(); ?>"/>
    <div class='form-actions'>
        <button type='submit' class='btn btn-primary'> Actualizar </button>
        <button type='submit' class='btn btn-danger' formaction="/clients/Client/delete"> Delete </button>
    </div> 
    <?php
        echo $this->form()->closeTag($form);
    ?>
    </div>    
  </div>
</div>

<script>

$("label span").each(function() {
    var $this = $(this);
    $this.replaceWith($("<label class='control-label'><strong>" + $this.html() + "</strong></label>"));
});

$("div label").each(function() {
    var $this = $(this);
    $this.replaceWith($("<div class='control-group'>" + $this.html() + "</div>"));
});

$('input').wrap('<div class="controls" />');

</script>