<?php	
	$clients = $this->allClients;

    $attrs = array(
      "clientId", 
      "First Name", 
      "Last Name", 
      "Accounts"
      );

?>

<table class='table'> 
  <thead>
    <tr>
      <?php
      foreach($attrs as $key) {
        echo "<th>" . $key . "</th>";
      }
      ?>
    </tr>
  </thead>
  <tbody>
    <?php
    foreach($clients as $tmp_client) {
      	echo "<tr>";
    ?>
    <td><a href="<?php echo $this->url('clients/Client', array('action'=>'show', 'clientId' => $tmp_client->getClientId() ));?>"> <?php echo $tmp_client->getClientId(); ?> </a></td>
    <td><a href="<?php echo $this->url('clients/Client', array('action'=>'show', 'clientId' => $tmp_client->getClientId() ));?>"> <?php echo ucfirst($tmp_client->getFirstName()); ?> </a></td>
    <td><a href="<?php echo $this->url('clients/Client', array('action'=>'show', 'clientId' => $tmp_client->getClientId() ));?>"> <?php echo ucfirst($tmp_client->getLastName()); ?> </a></td>
    <td><a href="<?php echo $this->url('clients/Client', array('action'=>'show', 'clientId' => $tmp_client->getClientId() ));?>"> <?php echo $tmp_client->getAccounts()->count(); ?> </a></td>
    
    <?php
    	echo "</tr>";
    }
    ?>
  </tbody>
</table>
