<?php 

$payments = $this->payments;
$accounts = $this->accounts;

$startDate = $this->rangeStart;
$endDate = $this->rangeEnd;


$amountDueByE = \Fundasol\Model\Fundasol::amountExpected($payments, $startDate, $endDate);
$amountDueByR = \Fundasol\Model\Fundasol::amountReality($payments, $startDate, $endDate);
$amountCollected = \Fundasol\Model\Fundasol::amountCollected($payments, $startDate, $endDate);
$amountOnTransit = \Fundasol\Model\Fundasol::amountOnTransit($payments);
$amountRequested = \Fundasol\Model\Fundasol::amountRequested($accounts);
$amountAvailable = \Fundasol\Model\Fundasol::amountAvailable($contributions, $payments);
$amountTotal = \Fundasol\Model\Fundasol::amountTotal($contributions);

?>

<h1> Fundasol <small> Fundacion Solidaridad </small> </h1>


<form method="post" action="/" class="form-inline">
	<input type="datetime" name="rangeStart"  value="<?php echo $startDate ?>" />
	<input type="datetime" name="rangeEnd" value="<?php echo $endDate ?>" />
	<input type="submit" class="btn" name="setRangeBtn" value="refresh" />
</form> 


<dl class="dl-horizontal">
	<dt>Expected</dt><dd><?php echo $amountDueByE . PHP_EOL; ?></dd>
    <dt>Reality</dt><dd><?php echo $amountDueByR . PHP_EOL; ?></dd>
    <dt>Collected</dt><dd><?php echo $amountCollected . PHP_EOL; ?></dd>
    <dt>On Transit</dt><dd><?php echo $amountOnTransit . PHP_EOL; ?></dd>
    <dt>Requested</dt><dd> <?php echo $amountRequested . PHP_EOL; ?></dd>
    <dt>Available</dt><dd><?php echo $amountAvailable . PHP_EOL; ?></dd>
    <dt>TOTAL</dt><dd><?php echo $amountTotal . PHP_EOL; ?></dd>
</dl>


<script>

$('input[name="rangeStart"]').datepicker({ 
    dateFormat: 'yy-mm-dd' , 
    beforeShowDay: function(date) {
        var day = date.getDay();
        return [(day != 0 && day != 6), ''];
    }
});

$('input[name="rangeEnd"]').datepicker({ 
    dateFormat: 'yy-mm-dd' , 
    beforeShowDay: function(date) {
        var day = date.getDay();
        return [(day != 0 && day != 6), ''];
    }
});

</script>