<?php 

$payments = $this->payments;

$startDate = \date("2013-09-08");
$endDate = \date("2013-09-13");


$amountDueByE = \Fundasol\Model\Fundasol::amountExpected($payments, $startDate, $endDate);
$amountDueByR = \Fundasol\Model\Fundasol::amountReality($payments, $startDate, $endDate);
$amountCollected = \Fundasol\Model\Fundasol::amountCollected($payments, $startDate, $endDate);
$amountOnTransit = \Fundasol\Model\Fundasol::amountOnTransit($payments);
$amountAvailable = \Fundasol\Model\Fundasol::amountAvailable($contributions, $payments);
$amountTotal = \Fundasol\Model\Fundasol::amountTotal($contributions);

?>

<h1> Fundasol <small> Fundacion Solidaridad </small> </h1>


<dl class="dl-horizontal">
	<dt>Expected</dt><dd><?php echo $amountDueByE . PHP_EOL; ?></dd>
    <dt>Reality</dt><dd><?php echo $amountDueByR . PHP_EOL; ?></dd>
    <dt>Collected</dt><dd><?php echo $amountCollected . PHP_EOL; ?></dd>
    <dt>On Transit</dt><dd><?php echo $amountOnTransit . PHP_EOL; ?></dd>
    <dt>Available</dt><dd><?php echo $amountAvailable . PHP_EOL; ?></dd>
    <dt>TOTAL</dt><dd><?php echo $amountTotal . PHP_EOL; ?></dd>
</dl>


