<?php
$account = $this->account;
$client = $this->account->getClient();
$client_html =  $client->getLastName() . ", " . $client->getFirstName();
$client_status_html = "Pending";
$payments = $account->getPayments();

$paymentAttrs = array(
  'Amount', 
  'Payment Number', 
  'Due Date', 
  'Paid Date',
  'Status'
  );

$isPending = false;
if ($account->getStatus() == \Account\Entity\Account::PENDING) {
  $isPending = true;
}


?>

  <h2> Account <?php echo $account->getAccountId(); ?> <small> <?php echo ucwords($client_html); ?></small> </h2>
  
  <div class='tabbable'>
    
    <ul class='nav nav-tabs'>
      <li class="<?php if (!$isPending) { echo 'active'; } else { echo 'hidden'; } ?>"><a href='#account_payments' data-toggle='tab'>Payments</a></li>
      <li class="<?php if ($isPending) { echo 'active'; } ?>"><a href='#account_info' data-toggle='tab'> Informacion</a></li>
    </ul>
    <div class='tab-content'>
      <div class="tab-pane <?php if ($isPending) { echo 'active'; } ?>" id='account_info'>
        <div class="row-fluid">
          <div class="span6">
            <dl class='dl-horizontal'>
              <dt> Needed By      </dt> <dd> <?php echo $account->getRequestDate(); ?> </dd>
              <dt> Payments Start </dt> <dd> <?php echo $account->getFirstPayDate(); ?> </dd>
              <dt> Amount         </dt> <dd> <?php echo $account->getAmount(); ?> </dd>
              <dt> Number Paid    </dt> <dd> <?php echo $account->getNPaid(); ?> / <?php echo $account->getNPayments(); ?> </dd>
              <dt> Pay Period     </dt> <dd> <?php echo $account->getPayPeriod(); ?> </dd>
              <dt> Status         </dt> <dd> <?php echo $account->getStatus(); ?> </dd>
            </dl>
          </div>
          <div class="span6">
            <h4> Report </h4>
            <?php echo $account->getHTMLReport(); ?>
          </div>
        </div>
        <?php
          if ($isPending) {
        ?>

        <form action="/accounts/Account/approve" method="post">
          <div class="form-actions">
            <input type="hidden" name="accountId" value="<?php echo $account->getAccountId(); ?>" />
            <button class="btn btn-primary" type="submit">Approve</button>
            <button class="btn btn-danger" type="submit" formaction="/accounts/Account/deny">Deny</button>
          </div>
        </form>

        <?php
          }
        ?>
      </div>
      <div class="tab-pane <?php if (!$isPending) { echo 'active'; } else { echo 'hidden';} ?>" id='account_payments'>
        <?php 
        if ($account->getStatus() == \Account\Entity\Account::OPEN) {
          echo '<form action="/accounts/Account/pay" method="post">' . PHP_EOL 
          . '<input type="hidden" name="accountId" value="' . $account->getAccountId() . '"/>' . PHP_EOL
          . '<input type="submit" class="btn" value="Hacer Un Pago"/>' . PHP_EOL
          . '</form>' . PHP_EOL;
        }
        ?>
        <table class='table'> 
          <thead>
            <tr>
              <?php
              if (count($payments) !== 0) {
                foreach($paymentAttrs as $attr ) {
                  echo "<th>" . $attr . "</th>";
                }
              }
              ?>
            </tr>
          </thead>
          <tbody>
            <?php
            foreach($payments as $tmp_payment) {
              if ($tmp_payment->getStatus() == \Payment\Entity\Payment::ONTIME) {
                echo "<tr class='success'>";
              } else if ($tmp_payment->getStatus() == \Payment\Entity\Payment::LATE) {
                echo "<tr class='warning'>";
              } else {
                echo "<tr>";
              }
              ?>
              <td><?php echo $tmp_payment->getAmount(); ?></td>
              <td><?php echo $tmp_payment->getPaymentNumber(); ?></td>
              <td><?php echo $tmp_payment->getDueDateStr(); ?></td>
              <td><?php echo $tmp_payment->getPaidTimeStampStr(); ?></td>
              <td><?php echo $tmp_payment->getStatus(); ?></td>
              <?php
              echo "</tr>";
            }
            ?>
          </tbody>
        </table>
      </div>
    </div>
  </div>