<?php	
	$accounts = $this->allAccounts;
  $attrs = array("Amount", "Start Week", "First Name", "Last Name", "status");
  ?>

<table class='table'> 
  <thead>
    <tr>
      <?php
      foreach($attrs as $key) {
        echo "<th>" . $key . "</th>";
      }
      ?>
    </tr>
  </thead>
  <tbody>
    <?php
    foreach($accounts as $tmp_account) {
      	if ($tmp_account->getStatus() == \Account\Entity\Account::OPEN) {
          echo "<tr class='success'>";
        } else {
          echo "<tr>";
        }
    ?>
    <td><a href="<?php echo $this->url('accounts/Account', array('action'=>'show', 'accountId' => $tmp_account->getAccountId() ));?>"> <?php echo $tmp_account->getAmount(); ?> </a></td>
    <td><a href="<?php echo $this->url('accounts/Account', array('action'=>'show', 'accountId' => $tmp_account->getAccountId() ));?>"> <?php echo $tmp_account->getFirstPayDateStr(); ?> </a></td>
    <td><a href="<?php echo $this->url('accounts/Account', array('action'=>'show', 'accountId' => $tmp_account->getAccountId() ));?>"> <?php echo ucfirst($tmp_account->getClient()->getFirstName()); ?> </a></td>
    <td><a href="<?php echo $this->url('accounts/Account', array('action'=>'show', 'accountId' => $tmp_account->getAccountId() ));?>"> <?php echo ucfirst($tmp_account->getClient()->getLastName()); ?> </a></td>
    <td><a href="<?php echo $this->url('accounts/Account', array('action'=>'show', 'accountId' => $tmp_account->getAccountId() ));?>"> <?php echo ucfirst($tmp_account->getStatus()); ?> </a></td>
    <?php
    	echo "</tr>";
    }
    ?>
  </tbody>
</table>
