<?php
  $account = $this->account;
  $client = $this->account->getClient();
  $client_html =  $client->getLastName() . ", " . $client->getFirstName();
  $client_status_html = "Pending";
  $form = $this->form;
  $form->prepare();
  $form->setAttribute('action', '/accounts/Account/edit');
  $form->setAttribute('method', 'post');
  $form->setAttribute('class', 'form-horizontal');

  $attrs = array(
    'startWeek',
    'amount', 
    'nPayments',
    'nPaid',
    'status'
    );

?>

<h2> Account <?php echo $account->getAccountId(); ?> <small> <?php echo ucwords($client_html); ?></small> </h2>
<div class='tabbable'>
  <ul class='nav nav-tabs'>
    <li class='active'><a href='#account_info' data-toggle='tab'> Informacion</a></li>
  </ul>
  
  <div class='tab-content'>
    
    <div class='tab-pane active' id='account_info'>
    <?php
    echo $this->form()->openTag($form);
    foreach ($attrs as $attr) {
      echo $this->formRow($form->get($attr));
    }
    //echo $this->formCollection($form);
    ?>
    <input type="hidden" name="accountId" value="<?php echo $account->getAccountId(); ?>"/>
    <div class='form-actions'>
        <button type='submit' class='btn btn-primary'> Actualizar </button>
        <button type='submit' class='btn btn-danger' formaction="/accounts/Account/delete"> Delete </button>
    </div> 
    <?php
        echo $this->form()->closeTag($form);
    ?>
    </div>    
  </div>
</div>

<script>

$("label span").each(function() {
    var $this = $(this);
    $this.replaceWith($("<label class='control-label'><strong>" + $this.html() + "</strong></label>"));
});

$("div label").each(function() {
    var $this = $(this);
    $this.replaceWith($("<div class='control-group'>" + $this.html() + "</div>"));
});

$('input').wrap('<div class="controls" />');

</script>