<?php 
echo $this->doctype(); 
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui-1.9.2.custom.css')
                        ->prependStylesheet($this->basePath() . '/css/custom.css')                        
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')                        
                         ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.js')
            ->prependFile($this->basePath() . '/js/jquery-ui-1.10.3.custom.min.js')            
            ->prependFile($this->basePath() . '/js/jquery-1.9.1.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-static-top" role="navigation">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="<?php echo $this->url('home') ?>">Fundasol</a>
                    <ul class="nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>">Home</a></li>
                        <li class='dropdown'>
                            <a href='#' class='dropdown-toggle' data-toggle='dropdown'>Clientes <span class="badge badge-inverse"> <?php echo \Client\Entity\Client::$count; ?> </span>
    </a>
                            <ul class='dropdown-menu'>
                                <li><a href="<?php echo $this->url('clients') ?>">Mostrar</a></li>
                                <li><a href="<?php echo $this->url('clients/Client', array("action" => "add")) ?>">Crear Nuevo</a></li>
                            </ul>
                        </li>
                        <li><a href="<?php echo $this->url('accounts/Account', array('action' => 'showAll')) ?>">Cuentas <span class="badge badge-inverse"> <?php echo \Account\Entity\Account::$count; ?> </span>
    </a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>1998 - 2013</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
