<?php
$contribution = $this->contribution;
$investor = $this->contribution->getInvestor();
$investor_html =  $investor->getLastName() . ", " . $investor->getFirstName();
?>

<h2> Contribution <?php echo $contribution->getContributionId(); ?> </h2>

<div class='tabbable'>
  
  <ul class='nav nav-tabs'>
    <li><a href='#contribution_info' data-toggle='tab'> Informacion </a></li>
  </ul>
  <div class='tab-content'>
    <div class='tab-pane active' id='contribution_info'>
      <div class="row-fluid">
        <div class="span6">
          <dl class='dl-horizontal'>
            <dt> Amount         </dt> <dd> <?php echo $contribution->getAmount(); ?> </dd>
            <dt> Status         </dt> <dd> <?php echo $contribution->getStatus(); ?> </dd>
          </dl>
        </div>
        <div class="span6">
        </div>
      </div>
    </div>
  </div>
</div>